# Generated by Django 5.0.4 on 2024-07-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="tag.tag"
            ),
        ),
    ]
