# Generated by Django 5.0.4 on 2024-05-14 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
