# Generated by Django 5.0.4 on 2024-05-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
