name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    name: Run tests throughout project
    runs-on: ubuntu-latest # operating system your code will run on
    steps:      
      - name: Setup Python Version
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11 # Install the python version needed
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.
      - name: Install Python dependencies
        run:  |
          cd django-blog/blog 
          pip install -r requirements.txt # Install the dependencies (if needed)
  
      - name: Run Django tests
        env: 
          SECRET_KEY: z4k(_--9o10ee$6)bn+zd8gis0^mi_cj3dvn=q=o-c6q#$61tf
        run: |           
          cd django-blog/blog
          python manage.py test . # run pytest test